# Language-specific netlify.toml for LANG_CODE
[build]
  publish = "public/LANG_CODE"
  command = "cd .. && hugo --gc --minify --buildFuture -d public/LANG_CODE --contentDir content/LANG_CODE"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../hugo.yaml ../themes/ ../layouts/ ../static/ ../assets/"

# Redirect apex domain to www version
[[redirects]]
  from = "https://confoot.DOMAIN_TLD/*"
  to = "https://www.confoot.DOMAIN_TLD/:splat"
  status = 301
  force = true

# Domain-based language selection
[[redirects]]
  from = "/*"
  to = "/LANG_CODE/:splat"
  status = 200
  conditions = {host = ["www.confoot.DOMAIN_TLD"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com; font-src 'self'; base-uri 'self'; form-action 'self'"
