[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://confoot.netlify.app/*"
  to = "https://www.confoot.eu/:splat"
  status = 301
  force = true

# Handle language-specific domains
[[redirects]]
  from = "https://www.confoot.cz/*"
  to = "https://www.confoot.eu/cs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.confoot.sk/*"
  to = "https://www.confoot.eu/sk/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.confoot.de/*"
  to = "https://www.confoot.eu/de/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; media-src 'self'; object-src 'none'; frame-src 'none';"
