[build]
  publish = "public"
  command = "hugo --gc --minify --buildFuture --buildDrafts --buildExpired --buildFuture"

[build.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://confoot.netlify.app/*"
  to = "https://www.confoot.eu/:splat"
  status = 301
  force = true

# Redirect apex domains to www versions
[[redirects]]
  from = "https://confoot.eu/*"
  to = "https://www.confoot.eu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.cz/*"
  to = "https://www.confoot.cz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.sk/*"
  to = "https://www.confoot.sk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.de/*"
  to = "https://www.confoot.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.gr/*"
  to = "https://www.confoot.gr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.hr/*"
  to = "https://www.confoot.hr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.lt/*"
  to = "https://www.confoot.lt/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.lv/*"
  to = "https://www.confoot.lv/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ru/*"
  to = "https://www.confoot.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.si/*"
  to = "https://www.confoot.si/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ro/*"
  to = "https://www.confoot.ro/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.li/*"
  to = "https://www.confoot.li/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.at/*"
  to = "https://www.confoot.at/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ch/*"
  to = "https://www.confoot.ch/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.pt/*"
  to = "https://www.confoot.pt/:splat"
  status = 301
  force = true

# Domain-based language selection with rewrites to language directories
# Czech domain - serve content from /cs/ subfolder
[[redirects]]
  from = "/*"
  to = "/cs/:splat"
  status = 200
  conditions = {host = ["www.confoot.cz"]}

# Slovak domain - serve content from /sk/ subfolder
[[redirects]]
  from = "/*"
  to = "/sk/:splat"
  status = 200
  conditions = {host = ["www.confoot.sk"]}

# German domain - serve content from /de/ subfolder
[[redirects]]
  from = "/*"
  to = "/de/:splat"
  status = 200
  conditions = {host = ["www.confoot.de"]}

# Greek domain - serve content from /gr/ subfolder
[[redirects]]
  from = "/*"
  to = "/gr/:splat"
  status = 200
  conditions = {host = ["www.confoot.gr"]}

# Croatian domain - serve content from /hr/ subfolder
[[redirects]]
  from = "/*"
  to = "/hr/:splat"
  status = 200
  conditions = {host = ["www.confoot.hr"]}

# Lithuanian domain - serve content from /lt/ subfolder
[[redirects]]
  from = "/*"
  to = "/lt/:splat"
  status = 200
  conditions = {host = ["www.confoot.lt"]}

# Latvian domain - serve content from /lv/ subfolder
[[redirects]]
  from = "/*"
  to = "/lv/:splat"
  status = 200
  conditions = {host = ["www.confoot.lv"]}

# Russian domain - serve content from /ru/ subfolder
[[redirects]]
  from = "/*"
  to = "/ru/:splat"
  status = 200
  conditions = {host = ["www.confoot.ru"]}

# Slovenian domain - serve content from /sl/ subfolder
[[redirects]]
  from = "/*"
  to = "/sl/:splat"
  status = 200
  conditions = {host = ["www.confoot.si"]}

# Romanian domain - serve content from /ro/ subfolder
[[redirects]]
  from = "/*"
  to = "/ro/:splat"
  status = 200
  conditions = {host = ["www.confoot.ro"]}

# Liechtenstein domain - serve content from /li/ subfolder
[[redirects]]
  from = "/*"
  to = "/li/:splat"
  status = 200
  conditions = {host = ["www.confoot.li"]}

# Austrian domain - serve content from /at/ subfolder
[[redirects]]
  from = "/*"
  to = "/at/:splat"
  status = 200
  conditions = {host = ["www.confoot.at"]}

# Swiss domain - serve content from /ch/ subfolder
[[redirects]]
  from = "/*"
  to = "/ch/:splat"
  status = 200
  conditions = {host = ["www.confoot.ch"]}

# Portuguese domain - serve content from /pt/ subfolder
[[redirects]]
  from = "/*"
  to = "/pt/:splat"
  status = 200
  conditions = {host = ["www.confoot.pt"]}

# English domain (primary) - serve content from /en/ subfolder
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  conditions = {host = ["www.confoot.eu"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com; font-src 'self'; base-uri 'self'; form-action 'self'"
