[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://confoot.netlify.app/*"
  to = "https://www.confoot.eu/:splat"
  status = 301
  force = true

# Handle the root domain properly
[[redirects]]
  from = "/"
  to = "/cs/"
  status = 302
  force = true
  conditions = {Language = ["cs"], Country = ["CZ"]}

[[redirects]]
  from = "/"
  to = "/sk/"
  status = 302
  force = true
  conditions = {Language = ["sk"], Country = ["SK"]}

[[redirects]]
  from = "/"
  to = "/de/"
  status = 302
  force = true
  conditions = {Language = ["de"], Country = ["DE", "AT", "CH", "LI"]}

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true

# Redirect apex domains to www versions
[[redirects]]
  from = "https://confoot.eu/*"
  to = "https://www.confoot.eu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.cz/*"
  to = "https://www.confoot.cz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.sk/*"
  to = "https://www.confoot.sk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.de/*"
  to = "https://www.confoot.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.gr/*"
  to = "https://www.confoot.gr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.hr/*"
  to = "https://www.confoot.hr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.lt/*"
  to = "https://www.confoot.lt/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.lv/*"
  to = "https://www.confoot.lv/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ru/*"
  to = "https://www.confoot.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.si/*"
  to = "https://www.confoot.si/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ro/*"
  to = "https://www.confoot.ro/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.li/*"
  to = "https://www.confoot.li/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.at/*"
  to = "https://www.confoot.at/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ch/*"
  to = "https://www.confoot.ch/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.pt/*"
  to = "https://www.confoot.pt/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; media-src 'self'; object-src 'none'; frame-src 'none';"
