[build]
  publish = "public"
  command = "hugo --gc --minify --buildFuture"

[build.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://confoot.netlify.app/*"
  to = "https://www.confoot.eu/:splat"
  status = 301
  force = true

# Redirect apex domains to www versions
[[redirects]]
  from = "https://confoot.eu/*"
  to = "https://www.confoot.eu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.cz/*"
  to = "https://www.confoot.cz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.sk/*"
  to = "https://www.confoot.sk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.de/*"
  to = "https://www.confoot.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.gr/*"
  to = "https://www.confoot.gr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.hr/*"
  to = "https://www.confoot.hr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.lt/*"
  to = "https://www.confoot.lt/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.lv/*"
  to = "https://www.confoot.lv/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ru/*"
  to = "https://www.confoot.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.si/*"
  to = "https://www.confoot.si/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ro/*"
  to = "https://www.confoot.ro/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.li/*"
  to = "https://www.confoot.li/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.at/*"
  to = "https://www.confoot.at/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ch/*"
  to = "https://www.confoot.ch/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.pt/*"
  to = "https://www.confoot.pt/:splat"
  status = 301
  force = true

# Domain-to-language directory mappings
# Czech domain - Root path
[[redirects]]
  from = "/"
  to = "/cs/"
  status = 200
  conditions = {host = ["www.confoot.cz"]}

# Czech domain - All other paths
[[redirects]]
  from = "/*"
  to = "/cs/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.cz"]}

# Slovak domain - Root path
[[redirects]]
  from = "/"
  to = "/sk/"
  status = 200
  conditions = {host = ["www.confoot.sk"]}

# Slovak domain - All other paths
[[redirects]]
  from = "/*"
  to = "/sk/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.sk"]}

# German domain - Root path
[[redirects]]
  from = "/"
  to = "/de/"
  status = 200
  conditions = {host = ["www.confoot.de"]}

# German domain - All other paths
[[redirects]]
  from = "/*"
  to = "/de/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.de"]}

# Greek domain - Root path
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  conditions = {host = ["www.confoot.gr"]}

# Greek domain - All other paths
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.gr"]}

# Croatian domain - Root path
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  conditions = {host = ["www.confoot.hr"]}

# Croatian domain - All other paths
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.hr"]}

# Lithuanian domain - Root path
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  conditions = {host = ["www.confoot.lt"]}

# Lithuanian domain - All other paths
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.lt"]}

# Latvian domain - Root path
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  conditions = {host = ["www.confoot.lv"]}

# Latvian domain - All other paths
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.lv"]}

# Russian domain - Root path
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  conditions = {host = ["www.confoot.ru"]}

# Russian domain - All other paths
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.ru"]}

# Slovenian domain - Root path
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  conditions = {host = ["www.confoot.si"]}

# Slovenian domain - All other paths
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.si"]}

# Romanian domain - Root path
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  conditions = {host = ["www.confoot.ro"]}

# Romanian domain - All other paths
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.ro"]}

# Liechtenstein domain - Root path
[[redirects]]
  from = "/"
  to = "/de/"
  status = 200
  conditions = {host = ["www.confoot.li"]}

# Liechtenstein domain - All other paths
[[redirects]]
  from = "/*"
  to = "/de/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.li"]}

# Austrian domain - Root path
[[redirects]]
  from = "/"
  to = "/de/"
  status = 200
  conditions = {host = ["www.confoot.at"]}

# Austrian domain - All other paths
[[redirects]]
  from = "/*"
  to = "/de/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.at"]}

# Swiss domain - Root path
[[redirects]]
  from = "/"
  to = "/de/"
  status = 200
  conditions = {host = ["www.confoot.ch"]}

# Swiss domain - All other paths
[[redirects]]
  from = "/*"
  to = "/de/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.ch"]}

# Portuguese domain - Root path
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  conditions = {host = ["www.confoot.pt"]}

# Portuguese domain - All other paths
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.pt"]}

# English domain (default) - Root path
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  conditions = {host = ["www.confoot.eu"]}

# English domain (default) - All other paths
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
  force = true
  conditions = {host = ["www.confoot.eu"]}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; media-src 'self'; object-src 'none'; frame-src 'none';"
