[build]
  publish = "public"
  command = "hugo --gc --minify -b https://www.confoot.eu/"

[build.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://confoot.netlify.app/*"
  to = "https://www.confoot.eu/:splat"
  status = 301
  force = true

# Redirect apex domains to www versions
[[redirects]]
  from = "https://confoot.eu/*"
  to = "https://www.confoot.eu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.cz/*"
  to = "https://www.confoot.cz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.sk/*"
  to = "https://www.confoot.sk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.de/*"
  to = "https://www.confoot.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.gr/*"
  to = "https://www.confoot.gr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.hr/*"
  to = "https://www.confoot.hr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.lt/*"
  to = "https://www.confoot.lt/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.lv/*"
  to = "https://www.confoot.lv/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ru/*"
  to = "https://www.confoot.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.si/*"
  to = "https://www.confoot.si/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ro/*"
  to = "https://www.confoot.ro/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.li/*"
  to = "https://www.confoot.li/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.at/*"
  to = "https://www.confoot.at/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.ch/*"
  to = "https://www.confoot.ch/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://confoot.pt/*"
  to = "https://www.confoot.pt/:splat"
  status = 301
  force = true

# Language path handling
[[redirects]]
  from = "/cs/*"
  to = "https://www.confoot.cz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/sk/*"
  to = "https://www.confoot.sk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/de/*"
  to = "https://www.confoot.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/gr/*"
  to = "https://www.confoot.gr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/hr/*"
  to = "https://www.confoot.hr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/lt/*"
  to = "https://www.confoot.lt/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/lv/*"
  to = "https://www.confoot.lv/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ru/*"
  to = "https://www.confoot.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/si/*"
  to = "https://www.confoot.si/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ro/*"
  to = "https://www.confoot.ro/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/li/*"
  to = "https://www.confoot.li/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/at/*"
  to = "https://www.confoot.at/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ch/*"
  to = "https://www.confoot.ch/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/pt/*"
  to = "https://www.confoot.pt/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/*"
  to = "https://www.confoot.eu/:splat"
  status = 301
  force = true

# Fallback redirect for root path
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; media-src 'self'; object-src 'none'; frame-src 'none';"
