# Wrangler configuration for local development
name = "confoot"
type = "javascript"
account_id = "" # You can add your Cloudflare account ID here
workers_dev = true
compatibility_date = "2025-03-06"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "hugo --gc --minify --cleanDestinationDir --enableGitInfo"
upload.format = "service-worker"

[build.upload]
dir = "public"

# Environment variables for local development
[vars]
HUGO_VERSION = "0.125.4"
HUGO_ENABLEGITINFO = "true"
