name = "confoot-domain-router"
main = ".cloudflare/workers/domain-router/index.js"
compatibility_date = "2023-10-30"
account_id = "" # Add your Cloudflare account ID
workers_dev = true
route = "*confoot.*/*"
zone_id = "" # Add your Cloudflare zone ID

[build]
command = "hugo --minify"

[site]
bucket = "./public"
