name = "confoot-domain-router"
type = "javascript"
account_id = "" # Add your Cloudflare account ID
workers_dev = true
route = "*confoot.*/*"
zone_id = "" # Add your Cloudflare zone ID

[site]
bucket = "./public"
entry-point = ".cloudflare/workers/domain-router"

[build]
command = "hugo --minify"
upload.format = "service-worker"
