# Cloudflare Pages configuration for ConFoot

[build]
command = "hugo --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.123.6"

[site]
bucket = "./public"
entry-point = ".cloudflare/workers/domain-router"
