# Language-specific netlify.toml for ro
[build]
  publish = "public"
  command = "hugo --gc --minify --buildFuture --contentDir content/ro --baseURL https://www.confoot.ro"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF content/ro/ hugo.yaml themes/ layouts/ static/ assets/"

# Redirect apex domain to www version
[[redirects]]
  from = "https://confoot.ro/*"
  to = "https://www.confoot.ro/:splat"
  status = 301
  force = true

# Domain-based language selection
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  conditions = {host = ["www.confoot.ro"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com; font-src 'self'; base-uri 'self'; form-action 'self'"
